# Generated by Django 5.0.3 on 2025-11-11 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "county_code",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                ("province", models.CharField(blank=True, max_length=64)),
                ("prefecture", models.CharField(blank=True, max_length=64)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("region_tag", models.CharField(blank=True, max_length=16)),
                ("is_target", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["province", "prefecture", "name"],
            },
        ),
        migrations.CreateModel(
            name="Surveyor",
            fields=[
                (
                    "surveyor_id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=32)),
                ("gender", models.CharField(blank=True, max_length=8)),
                ("school", models.CharField(blank=True, max_length=64)),
                ("education_level", models.CharField(blank=True, max_length=32)),
                ("major", models.CharField(blank=True, max_length=64)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("team_id", models.CharField(blank=True, max_length=16)),
                ("role", models.CharField(blank=True, max_length=32)),
                ("batch_label", models.CharField(blank=True, max_length=32)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("interview_completed", models.PositiveIntegerField(default=0)),
                ("interview_pending", models.PositiveIntegerField(default=0)),
                ("expertise", models.TextField(blank=True)),
                ("training_completed", models.BooleanField(default=False)),
                ("equipment_status", models.CharField(blank=True, max_length=32)),
                ("notes", models.TextField(blank=True)),
                (
                    "primary_county",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_surveyors",
                        to="core.county",
                    ),
                ),
            ],
            options={
                "ordering": ["surveyor_id"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "interview_id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("interviewee_id", models.CharField(blank=True, max_length=32)),
                ("interviewee_name", models.CharField(blank=True, max_length=32)),
                ("interviewee_profile", models.TextField(blank=True)),
                ("transcript", models.TextField()),
                ("interview_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=128)),
                (
                    "quality_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "county",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviews",
                        to="core.county",
                    ),
                ),
                (
                    "surveyor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviews",
                        to="core.surveyor",
                    ),
                ),
            ],
            options={
                "ordering": ["-interview_date", "interview_id"],
            },
        ),
        migrations.CreateModel(
            name="CountyStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("payload", models.JSONField()),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="core.county",
                    ),
                ),
            ],
            options={
                "ordering": ["county__county_code", "-year"],
                "unique_together": {("county", "year")},
            },
        ),
    ]
